### ISSUE TITLE
Documentation on GitHub wiki

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#10]
Move documentation from old wiki to GitHub. Most articles may require reformatting for better looking.
### Installation manuals
- [x] Installation on Windows;
- [x] Installation on Mac;
- [x] Installation on Linux (for supported CPUs);
- [x] Installation on POSIX systems (Linux general, BSD, etc.).
### Compiling and distributing (advanced)
- [x] Build the latest development version;
- [x] Cross compiling;
- [x] Packaging.
### Configuration
- [x] Performance tips;
- [x] Choosing a cipher;
- [x] NZBGet behind other web-server.
### Usage
- [x] Catalog of post-processing scripts;
- [x] RSS and duplicate check;
- [x] VideoSort;
- [x] Command line reference.
### Extend
- [x] Extension scripts;
- [x] RPC API reference;
### Other
- [x] History (ChangeLog).
