### ISSUE TITLE
Source code naming convention

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#103]
For motivation see #88.

NZBGet code base is old. The project was started in 2004 and from the beginning uses [hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation) for identifiers. No one uses it nowadays anymore since it does more harm than good.

The naming changes can be done for example using global text replacements. The big problem here is to guarantee that the code works as before.
### Work items

_This list is continuously updated._

**1. local variables, member variables and function parameters:**
- [x] define new naming convention;
- [x] do total renaming;
- [x] make sure everything is intact after the global naming change;
- [x] review conditional code paths;
- [x] review results and make additional manual renamings where appropriate.

**1.5. repeat step 1 for folder "tests":**
- [x] do total renaming;
- [x] make sure everything is intact after the global naming change.

**2. normalize acronyms:**
- [x] do identifier renaming;
- [x] rename related source files;
- [x] make sure everything is intact after the global naming change.

**3. global variables:**
- [x] define new naming convention;
- [x] do total renaming;
- [x] make sure everything is intact after the global naming change.

**Comment by hugbug** [comment]
## Step 1: local variables, member variables and function parameters

In older code:

``` C++
// OLD
class Tokenizer
{
private:
    char                m_szDefaultBuf[2014];
    char*               m_szDataString;
    bool                m_bInplaceBuf;
    const char*         m_szSeparators;
    char*               m_szSavePtr;
    bool                m_bWorking;

public:
                        Tokenizer(const char* szDataString, const char* szSeparators);
                        Tokenizer(char* szDataString, const char* szSeparators, bool bInplaceBuf);
                        ~Tokenizer();
    char*               Next();
};
```

**Requirement:**
We want to remove type prefixes (such as `sz` for strings, `b` for booleans, etc) for local variables, member variables and function parameters. Variable names must be written in **camelCase** (starting with low case character).

The new code should look like this:

``` C++
// NEW
class Tokenizer
{
private:
    char                m_defaultBuf[2014];
    char*               m_dataString;
    bool                m_inplaceBuf;
    const char*         m_separators;
    char*               m_savePtr;
    bool                m_working;

public:
                        Tokenizer(const char* dataString, const char* separators);
                        Tokenizer(char* dataString, const char* separators, bool inplaceBuf);
                        ~Tokenizer();
    char*               Next();
};
```

**Comment by hugbug** [comment]
## How the step 1 was done
- a script was written to rename all related variables - [rename_vars.py](https://gist.github.com/hugbug/102bae8f586264dde61f);
- the source code was processed with the script;
- an attempt to compile the project was made, which has failed;
- compiler errors (name conflicts) were fixed;
- the generated executable was compared to the original one; it was found that they were not identical (details about comparison of executables see below);
- the code was compiled once again using compiler option "hidden local variables". All warnings were checked and few errors were found and fixed;
- the original code was processed using another script -  [rename_vars_warn.py](https://gist.github.com/hugbug/102bae8f586264dde61f) (scroll to the second script). All reported critical places were checked. However nothing more were discovered in addition to already fixed errors and warnings;
- the generated executable was compared to the original one once again: one difference was found; the related source code place was found with the help of disassembler; and fixed.
- the generated executable was compared to the original one and this time they were identical.

**Comment by hugbug** [comment]
## Comparing executables

In order to achieve the goal **"make sure everything is intact after the global naming change"** we needed a way to compare executables before and after global renaming.

MS Visual C++ and Clang didn't play well in this regard. Produced executables were different even after a small test renaming of one identifier, or even when nothing was changed.

It did go much better with GCC.

### Preparing GCC build
1. First we need to disable optimizations by using optimization mode `-O0`. For some reason optimized builds differ. My guess is this is happening because of some kind of sorting involved where identifier names have effect on assigned memory addresses.
2. The debug information should also not be present in the executable - either don't use option `-g` or do `strip <executable>` after making.
3. For linking the linker flag `-Wl,--build-id=none` must be used to disable generating of build-id. Otherwise the executable will not match. Add the parameter to variable `LDFLAGS` in the `Makefile` by editing the file before compiling.

### Comparing binary files

I use [Hex Fiend](https://github.com/ridiculousfish/HexFiend/), a tool for Mac OS X.

### What to do if files differ

First check how many differences are there. If the hundreds of them were reported that can mean the binaries were compiled with different compiler settings. Check compiler flags. If they are OK there are probably many side effects in the code. Does the program run at all?

I did have many differences first. So I've checked every compiler warning produced by option "hidden local variables". It did help to reduce the number of differences to only one.

### How to find the place in the source code which corresponds to that binary difference?
- I recompiled the code with option `-g`;
- disassembled the binary using **objdump**:
  
  ``` shell
  objdump -S -C nzbget > output.txt
  ```
- opened the output file in a text editor and used search function where search pattern was a few hex bytes at place in question (which I saw in the diff tool). It's important to make sure the search pattern find only one unique place.
- the output file contains the source code intermixed with the disassembly code and raw hex data.

Once the place in the raw hex data was found I immediately saw the corresponding source line, which I could easily match with the original source file and line. It took some time to find out what was wrong at this place and to fix the error.

## Limitations

Since we compare the executables that means that only the code which was used to generate these executable is checked for correctness. It sounds obvious but if the code contains conditional complier directives (**#ifdef**) only the code paths which were active during build are checked.

For NZBGet that means that all Windows-specific code wasn't checked for correctness since the compilation was performed on a Linux machine using GCC. Fortunately there is not too many Windows-specific code in NZBGet but it has to be manually reviewed and tested.

**Comment by hugbug** [comment]
## Step 2: normalize acronyms

That's a simple thing. We want identifiers like `NZB` or `URL` to be `Nzb` or `Url`. This include:
- variables;
- type names;
- file names.

The first post updated to include new work items.

List of used acronyms: NZB, URL, ID, NNTP, TLS, NT (NTService -> WinService).

**Comment by hugbug** [comment]
## Step 1.5: repeat step 1 for folder "tests"

During step 1 the variables were renamed for directory "daemon". We should do the same for directory "tests".

**Comment by hugbug** [comment]
## How the step 2 was done
- another helper script was written to rename acronyms - [rename_acronyms.py](https://gist.github.com/hugbug/102bae8f586264dde61f);
- the source code was processed with the script;
- an attempt to compile the project was made, which has succeeded;
- the generated executable was compared to the original one;
- files were not identical. The differences were reviewed and they all were in strings containing changed class names. They were probably part of RTTI. The differences were accepted.

**Comment by hugbug** [comment]
## Step 3: global variables

In older code:

``` C++
Thread* g_pFrontend = NULL;
CommandLineParser* g_pCommandLineParser = NULL;
ServerPool* g_pServerPool = NULL;
QueueCoordinator* g_pQueueCoordinator = NULL;
int g_iArgumentCount;
char* (*g_szEnvironmentVariables)[] = NULL;
```

**Requirement:** we want to remove type prefix (p, i, sz). In contrast to local variables whose names start with lower case character the global variable names should start with upper case character. Global variables are used in NZBGet mostly as singletons. After renaming their names will consist of class name  with `g_`-prefix. For example:

``` C++
Thread* g_Frontend = NULL;
CommandLineParser* g_CommandLineParser = NULL;
ServerPool* g_ServerPool = NULL;
QueueCoordinator* g_QueueCoordinator = NULL;
int g_ArgumentCount;
char* (*g_EnvironmentVariables)[] = NULL;
```

### Implementation
- another script was written to help with this - [rename_globals.py](https://gist.github.com/hugbug/102bae8f586264dde61f);
- after renaming the binary content was checked for identity with the version before renaming.
