### ISSUE TITLE
FreeBSD installer

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#124]
We need an installer package for FreeBSD similar to the existing Linux installer. That will make the installation of FreeBSD and in particular on FreeNAS easier.

List of to do's:
- [x] prepare compiler toolchain to build NZBGet binaries for FreeBSD;
- [x] add script `build-toolchain-freebsd` to distribution archive (update Makefile);
- [x] update `build-info-txt`;
- [x] extend script `build-nzbget` to work with new toolchain;
- [x] extend script `build-unpack` to work with new toolchain;
- [x] make sure `installer.sh` correctly works on FreeBSD;
- [x] make sure `install-update.sh` correctly works on FreeBSD;
- [x] configure update-info-file on web server.

**Comment by hugbug** [comment]
## Prepare compiler toolchain to build NZBGet binaries for FreeBSD

We could build nzbget binaries for FreeBSD on FreeBSD host but that involves an additional VM in the build process of preparing of new releases. Instead we use the existing Linux VM where the Linux binaries are produced.

GCC makes it possible. We create a cross-compiling toolchain which runs on Linux and produces binaries for FreeBSD.

The process of creating toolchain is documented in the script-file [linux/build-toolchain-freebsd](https://github.com/nzbget/nzbget/blob/124-freebsd-installer/linux/build-toolchain-freebsd).

It creates toolchain using the most recent (at this time) versions of Binutils and GCC.

**Comment by hugbug** [comment]
## Supported FreeBSD platform variants
- Currently we support only **x86_64** on FreeBSD. Other CPU-architectures can be added if necessary.
- We use FreeBSD version **9.1** as a base. The produced binaries work on newer versions too - tested with **10.2**. They even work on **8.3** too (nice to know).

**Comment by hugbug** [comment]
Everything implemented. The installer package for FreeBSD will be provided with the next testing release. If anyone wants to test it before that happens please drop me a note.
