### ISSUE TITLE
Activate C++14 compiler features

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#125]
For motivation see #88.
This is related to #101.

To use new C++ features we have already upgraded to newer compilers. However in order to activate these new features current compilers requires extra parameters.

In this issue:
- [x] update Linux build script to activate C++14 when compiling NZBGet;
- [x] update documentation for those who compile on their own with hints on how to activate C++14 in GCC and Clang;
- [x] extend configure script to check for required compiler features.

**Comment by hugbug** [comment]
Added compiler features check. Compiling now works without explicit setting of compiler flags, with usual

``` shell
./configure
make
```

It should automatically add required compiler switches.

It also reports an error if compiler is too old. The check can be disabled with `./configure --disable-cpp-check`, in which case required compiler options must be set via cpp-flags manually.
