### ISSUE TITLE
Historical releases

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#2]
- [x] rename tags from format xx.x to vxx.xx, for example "15.0" becomes "v15.0", to follow git standard on tag naming;
- [x] upload release files and notes for actual stable release 15.0 and the previous releases 14.0, 14.1, 14.2;
- [x] put release notes for older releases;
- [x] upload release files for older releases.

**Comment by hugbug** [comment]
All done.
