### ISSUE TITLE
Rar-rename: deobfuscation of rar-archives without par-files

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#288]
_Idea, reverse engineering and reference script implementation by @prinz23._

Sometimes downloads with obfuscated file names do not include par-files or the par-files were created after obfuscation of file names. Such downloads cannot be unpacked by NZBGet as unrar fails to process archives with non-sequential file names.

An inspection of rar format has shown that the rar headers include information about volume number. Using this information the files can be renamed to have sequential file names, which can then be successfully unpacked by unrar.

There are four rar formats to distinguish:
- rar3 (also used by rar4);
- rar3 encrypted (also used by rar4);
- rar5;
- rar5 encrypted.
### Documentation
- for rar 3/4: http://forensicswiki.org/wiki/RAR;
- for rar 5: http://www.rarlab.com/technote.htm.
### Tasks
- [x] create empty rar-renamer module with unit-tests;
- [x] support rar3 files;
- [x] support rar5 files;
- [x] implement file renaming;
- [x] integrate as post-processing stage;
- [x] create functional tests;
- [x] support rar5 encrypted files;
- [x] support rar3 encrypted files;
- [x] GnuTLS for encrypted files as alternative to OpenSSL.

**Comment by hugbug** [comment]
An option to prevent renaming of certain file types is needed. See forum topic [How to stop unpacking CBR extension?](http://forum.nzbget.net/viewtopic.php?f=3&t=2692).
