### ISSUE TITLE
Multi post-processing: non-exclusive par-repair

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#291]
This issue defines a new feature resulted from discussion in #290.

Currently post-processor works out one item at a time. If an item requires repair that process can take very long. In that time the post-processing queue may grow and many items which do not require repair wait for their turn to be processed. Post-processing steps required for other (non damaged) items may not require that much CPU power (which is used by par-repair) and such items could be possibly processed parallel with the repairing item.
### Tasks:
- [x] refactor code to make par-repair non global for easier management of post-processing steps;
- [x] make it possible to process more than one item at the same time;
- [x] create new option to enable/disable multi processing;
- [x] functional tests to cover new behavior;
- [x] fix global cout/cerr in par2-module to prevent crashes when executing two par2-instances;
- [x] options ParPauseQueue, UnpackPauseQueue, PostPauseQueue should work properly.

**Comment by hugbug** [comment]
The implementation has gone beyond the original idea. With new option **PostStrategy** the multi-processing of pp-items can be configured in four ways:

![screen shot 2016-10-15 at 13 04 26](https://cloud.githubusercontent.com/assets/3368402/19409583/25db1df8-92d7-11e6-9032-4e41f43ff3c1.png)
