### ISSUE TITLE
Reorder queued items with drag and drop

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#301]
An ability to reorder queued items with drag and drop has been requested on regular basis.

### Tasks
- [x] drag and drop handling in web-interface UI;
- [x] extend API if necessary;
- [x] unit or functional tests for API extension;
- [x] support for touch devices;
- [x] refactor: move code into tasttable.js unit for more general approach (and possible use of drag-n-drop in other UI places);
- [x] polishing of UI.
