### ISSUE TITLE
TLS/SSL certificate verification

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#339]
NZBGet supports TLS/SSL for communication with news and web servers. Connections are encrypted but the implementation lacks an important step - server certificate verification. As a result the security is reduced, in particular undetectable Man-in-the-Middle attacks (MitM) are possible.

Further details can be found in discussion #332.

To improve security NZBGet should implement server certificate verification, including hostname validation.

NZBGet can be compiled with either OpenSSL or GnuTLS. Since these two libraries have different API the certificate verification in NZBGet requires two implementations.

### Tasks:
- [x] general certificate verification when compiling with OpenSSL;
- [x] hostname verification when compiling with OpenSSL;
- [x] general certificate verification when compiling with GnuTLS;
- [x] hostname verification when compiling with GnuTLS;
- [x] integrate root certificate store file into Windows installer;
- [x] integrate root certificate store file into OSX installer;
- [x] integrate root certificate store file into Linux/FreeBSD installer;
- [x] optional: automatic refresh of root certificate store file during setup build;
- [x] write wiki page about how to deal with verification errors.
