### ISSUE TITLE
Migrate documentation from GitHub wiki to GitHub pages

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#383]
NZBGet web-site (main page and download page) is hosted on GitHub pages. The content is written in plain html. That is OK for two pages which rarely change. For documentation it was convenient to use wiki on GitHub as this allowed to write docs in markdown with little formatting as opposed to plain html.

Since end of 2016 GitHub pages support generating of html pages from markdown documents. This makes it possible to write documentation with the same comfort as using GitHub wiki (in markdown with preview) but brings many additional features which were not available in wiki; the most important are:
- own html style;
- URLs on nzbget.net domain;
- own header and footer;
- additional html formatting where necessary.

Task list:
- [x] move documents from GitHub wiki to GitHub pages;
- [x] configure theme templates;
- [x] update redirects;
- [x] update links on main documentation pages;
- [x] update links on other pages;
- [x] create sidebar for documentation pages;
- [x] write redirecting stubs on all old wiki pages.
