### ISSUE TITLE
Spin locks causing hanging

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#41]
## Problem

A problem on Drobo NAS was reported. The program was sometimes hanging during par-repair when multithreading par-repair was active (option _ParThreads_).
After investigation it was found the program was hanging in the system function _pthread_spin_lock_.

The spin locks are alternative to mutexes and can provide performance gain in certain situations. In NZBGet spin locks are used only in two cases:
- during par-repair if multicore par-repair is active - to synchronize repair threads;
- if option **AccurateRate** is active - to synchronize download threads.

Spin locks can be always replaced by mutexes. Furthermore not all platforms support spin locks (for example Mac OS X doesn't and not every Linux system has them). NZBGet uses spin locks if available, otherwise it falls back to mutexes.
## Steps to reproduce

Although the problem was initially reported during par-repair the easier way to reproduce is:
- activate option **AccurateRate**;
- download something.

If the system has problem with spin locks the download will soon stop.
## Tasks:
- [x] deactivate the usage of spin locks in builds included in Linux installer;
- [x] investigate if spin locks provide any measurable performance gain in NZBGet;
- [x] if there are no any advantages - remove spin locks from the code.

**Comment by hugbug** [comment]
Made tests on a Linux box with mipsel CPU (2x400MHz). Don't see any performance gain when using spin locks. Quite the contrary- the mutex version downloads even faster.

@ftischhauser: could you please make a test on Windows?
- activate option **AccurateRate**, download something and measure the speed and CPU usage;
- then comment out "#define HAVE_SPINLOCK" in "daemon\windows\win32.h", recompile and measure again.

Are there any difference? Which is better?
Thank you.

**Comment by hugbug** [comment]
Tested by @ftischhauser:

> I can't tell any difference between these two builds with accurate rate turned on

Thanks for testing!

That means the support for spinlocks can be completely removed from the program as it doesn't bring any advantages.
