### ISSUE TITLE
Let CertStore contain both file and directory at the same time

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#411]
Although the description of option **CertCheck** in NZBGet says that it can be either file or a directory, the root cert store in openssl can use both simultaneously - the file (with a bunch of certificates) and a directory (for additional certificates).

The simultaneous usage has advantages when using Let's Encrypt certificates in NZBGet's web-server. See discussion in #403.

**TODO:** either split **CertStore** into two options **CertStoreFile** and **CertStoreDir** or keep using **CertStore** but allow entering both a file and a directory there, separated by semicolon:
```
CertStore=${AppDir}/cacert.pem;${AppDir}/mycerts
```

Related (from the same topic):
The internal root cert store should be initialised before loading server certificate into NZBGet's web-server. That allows to send the full certificate chain to clients.

**Task list:**
- [ ] allow directory and file in CertStore for OpenSSL;
- [ ] allow directory and file in CertStore for GnuTLS;
- [ ] load root cert store before binding when using OpenSSL;
- [ ] load root cert store before binding when using GnuTLS.

**Comment by jbrodriguez** [comment]
Hi, I'm trying to run nzbget under macOS from the command line (haven't installed the app).

```
nzbget -s -c /path/to/config
```

I get these errors

```
Could not set certificate store location: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib
Could not set certificate store location: error:2006D080:BIO routines:BIO_new_file:no such file
Could not set certificate store location: error:02001002:system library:fopen:No such file or directory
```

I think it's related to this issue.

My settings are

```
CertCheck=yes
CertStore=/etc/ssl/cert.pem
```

That's the default cert.perm in macOS, but I also tried with homebrew installed openssl's ```/usr/local/etc/openssl/cert.pem```

Any thoughts ?

**Comment by hugbug** [comment]
> No such file or directory

That message is unambiguous. Check your config-file, maybe it has multiple entries for CertStore or type in the path.

`CertStore=/etc/ssl/cert.pem` works for me; using binary from the app; you can get the binary by browsing app package content.

**Comment by jbrodriguez** [comment]
Let me tell you that you're the man @hugbug !

I had duplicate CertStore and CertCheck (copied my nzbget.conf from a previous install that worked with NzbGet.app).
