### ISSUE TITLE
Cross-compiling for FreeBSD using Clang

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#425]
There is an issue with the latest version of FreeBSD which was reported on forum in topic [Segmentation Fault after upgrading to FreeBSD 11.1](https://forum.nzbget.net/viewtopic.php?f=3&t=2973). NZBGet crashes during downloading, easy to reproduce.

The issue seems to be in the incompatibility of used cross-compiling tools with the latest FreeBSD version. Currently our cross-compiling toolchain is based on GCC.

In newer versions of FreeBSD the default system compiler was changed from GCC to Clang. Therefore a cross-compiling toolchain based on Clang may work better.

In this issue:
- [x] build cross-compiling toolchain based on Clang;
- [x] do tests on different FreeBSD versions;
- [x] replace GCC toolchain with Clang toolchain when creating NZBGet installer for FreeBSD.
