### ISSUE TITLE
LGTM integration

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#604]
Thanks to #582 I now know about [lgtm.com](https://lgtm.com), a code analysis tool, which can integrate with GitHub and is free for open source projects.

For proper analysis the integration has to be configured:
- [x] enable pull request analysis;
- [x] create proper configuration file in nzbget repository. This is needed at least to exclude library files from results;
- [x] fix alerts for C++;
- [x] fix alerts for JavaScript.
