### ISSUE TITLE
Update unrar to 5.7 and 7-zip to 19.0

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#618]
In this issue:
- [x] Build unrar 5.7 for Linux, BSD and Android;
- [x] Build unrar 5.7 for Mac;
- [x] Update unrar to 5.7 on Windows;
- [x] Improve Windows installer to provide unrar in 32 bit and 64 bit variants;
- [x] Update 7-zip to 19.0 on Windows;
- [x] Improve Windows installer to provide 7-zip in 32 bit and 64 bit variants;
- [x] Update 7-zip to 16.02 on Mac (was 9.20 still);

7-zip on Linux, BSD, Android and Mac remains at version 16.02 as there is no newer version for these platforms.
