### ISSUE TITLE
Advanced search capabilities

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#72]
Currently the search box can search for any word from the typed phrase.
An attempt to improve the search capabilities was made in #36 but it doesn't work very well.
![quickfilter](https://cloud.githubusercontent.com/assets/3368402/9324892/966870ee-458e-11e5-8052-7918a95ade4d.png)

**Task:** implement a proper parser with OR, AND, NOT, parenthesis and ability to search throw specified fields.
- [x] implement advanced parser;
- [x] make the parser default for all existing lists;
- [x] search specific fields;
- [x] create documentation page; 
- [x] advanced search in settings.

**Comment by hugbug** [comment]
Done.

**Comment by hugbug** [comment]
Bug reported on [forum](http://forum.nzbget.net/viewtopic.php?f=3&t=2132):

> When using the search/filter box in an NZB files list the filter gets applied to the next NZB files list you click into as well. i.e. the filter does not get cleared/reset when you close out of the files box or go back into it.
> 
> How to reproduce:
> 
> Click an NZB in the queue.
> Go to the files dialog box
> Type something in the search to filter the files list
> Click cancel or save to close the dialog
> 
> Click the same or another NZB in the queue
> Go to the files dialog box
> The Search box (DownloadsEdit_FileTable_filter) is blank, yet the same filter is still applied
> Press space and backspace to clear the filter and all the files show.
