### ISSUE TITLE
Modern C++

### ISSUE THREAD

**Issue by hugbug** [nzbget/nzbget#88]
### Intro

When developing NZBGet one of the priorities always was to make it work on as many devices as possible. Due to a wide variety of platforms we could not control which version of compiler is used. To make it compatible even with old compilers NZBGet was targeting old C++ versions.

In last years C++ has been evolved dramatically. New versions were standardized by ISO as C++11 and lately C++14. These new standards bring many interesting features to the language making it much more pleasure to work with.

In the meantime major Linux distributions have updated their compilers to GCC 5, which supports C++14. Xcode on OS X includes C++14 compatible compiler. MS Visual Studio 2015 is compatible with C++14 as well.

Moreover after the introducing of universal Linux installer in v15 we now offer precompiled binaries for three major platforms (Windows, Linux, OS X). This makes it less important which compiler is installed on user machine since only few users compile themselves.

So now it is the time to upgrade the code base of NZBGet to C++14.
### First steps (prerequisites)
- [x] upgrade Linux build machine to use GCC 5.2 for all targets included in universal installer (#101);
- [x] upgrade Window build machine to use MS Visual Studio 2015 (#102).
### Deep refactoring and new C++ features
- [x] change source code naming convention (#103);
- [x] put all external headers together (#115);
- [x] improve code formatting (#176);
- [x] use precompiled headers (#115);
- [x] use size specific integer types (#116);
- [x] use string classes for managed string handling (#126);
- [x] use namespaces (#133);
- [x] `nullptr` instead of `NULL` (#138);
- [x] store objects directly in containers (#143);
- [x] avoid "malloc/free" for temporary buffers (#156);
- [x] for-range loop with iterators (#152);
- [x] use lambdas with containers (#154);
- [x] prefer references to pointers (#151);
- [x] prefer stack objects (#167);
- [x] prefer safe memory management alternatives to plain "malloc/free" (#172);
- [x] use in-class member initializers (#175);
- [x] use std::shared_ptr for shared resources (#182);
- [x] indicate object ownership with std::unique_ptr (#148, #168);
- [x] exception safe (RAII) lock handling (#185).
### New standard libraries
-  ~~built-in **regex**-library instead of external regex~~ - _optional_;
-  ~~built-in **concurrency**-library instead of system specific pthreads or windows threads~~ - _optional_.

**Comment by hugbug** [comment]
### GCC versions

C++ standard is big and complex. Compilers add support for certain C++ feature incrementally. GCC claims full support for C++14 in GCC 5.0. However many features were added in older GCC versions, since it was a long process of adding them through the years.

According to [this chart](http://en.cppreference.com/w/cpp/compiler_support) the C++11 features were fully implemented in GCC 4.8; C++14 in GCC 5.0.

Even if your system compiler is an older version it should be possible to build a toolchain with newer compiler version (not necessary to install it system wide) but that is of course extra efforts.

**Comment by hugbug** [comment]
> #### New standard libraries
> - built-in regex-library instead of external regex;
> - built-in concurrency-library instead of system specific pthreads or windows threads.

The switch may bring compatibility and stability issues. The implementations of regex seem to not be fully standard compliant. Every compiler has its own implementation. Currently we use the same library on all platforms.

As for **concurrency** this requires more testing and will probably not bring much to NZBGet.

I've decided to not switch to new standard libraries for **regex** and **concurrency** for now.

**Comment by hugbug** [comment]
**Considering the migration to Modern C++ completed.**

That was a lot of work and the code base looks much much nicer now.
